function Ydot = EQa_CRTPB_NL(MU,x,xdot,y,ydot,z,zdot)
%EQA_CRTPB_NL
%    YDOT = EQA_CRTPB_NL(MU,X,XDOT,Y,YDOT,Z,ZDOT)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Dec-2018 15:10:33

t2 = MU+x-1.0;
t3 = MU.*2.0;
t4 = x.*2.0;
t5 = MU+x;
t6 = y.^2;
t7 = z.^2;
t8 = t2.^2;
t9 = t6+t7+t8;
t10 = 1.0./t9.^(3.0./2.0);
t11 = MU-1.0;
t12 = t5.^2;
t13 = t6+t7+t12;
t14 = 1.0./t13.^(3.0./2.0);
Ydot = [xdot;ydot;zdot;x+ydot.*2.0-(MU.*t10.*(t3+t4-2.0))./2.0+(t11.*t14.*(t3+t4))./2.0;xdot.*-2.0+y-MU.*t10.*y+t11.*t14.*y;-MU.*t10.*z+t11.*t14.*z];
