function Ydot = EQa_CRTPB_Linear(MU,Ydot0,dY,x,y,z)
%EQA_CRTPB_LINEAR
%    YDOT = EQA_CRTPB_LINEAR(MU,YDOT0,DY,X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Dec-2018 15:10:33

t2 = Ydot0+dY;
t3 = MU+x;
t4 = MU+x-1.0;
t5 = y.^2;
t6 = z.^2;
t7 = MU-1.0;
t13 = MU.*2.0;
t14 = x.*2.0;
t8 = t13+t14;
t9 = t3.^2;
t10 = t5+t6+t9;
t11 = t4.^2;
t12 = t5+t6+t11;
t15 = t13+t14-2.0;
t16 = 1.0./t10.^(5.0./2.0);
t17 = 1.0./t12.^(5.0./2.0);
t18 = MU.*t15.*t17.*y.*(3.0./2.0);
t19 = dY.*(t18-t7.*t8.*t16.*y.*(3.0./2.0));
t20 = Ydot0+t19;
t21 = 1.0./t10.^(3.0./2.0);
t22 = t7.*t21;
t23 = 1.0./t12.^(3.0./2.0);
t24 = dY.*2.0;
t25 = MU.*t15.*t17.*z.*(3.0./2.0);
t26 = dY.*(t25-t7.*t8.*t16.*z.*(3.0./2.0));
t27 = Ydot0+t26;
t28 = MU.*t17.*y.*z.*3.0;
t29 = t28-t7.*t16.*y.*z.*3.0;
t30 = dY.*t29;
t31 = Ydot0+t30;
Ydot = reshape([Ydot0,Ydot0,Ydot0,Ydot0+dY.*(t22-MU.*t23-t7.*t8.^2.*t16.*(3.0./4.0)+MU.*t15.^2.*t17.*(3.0./4.0)+1.0),t20,t27,Ydot0,Ydot0,Ydot0,t20,Ydot0+dY.*(t22-MU.*t23+MU.*t5.*t17.*3.0-t5.*t7.*t16.*3.0+1.0),t31,Ydot0,Ydot0,Ydot0,t27,t31,Ydot0+dY.*(t22-MU.*t23+MU.*t6.*t17.*3.0-t6.*t7.*t16.*3.0),t2,Ydot0,Ydot0,Ydot0,Ydot0-t24,Ydot0,Ydot0,t2,Ydot0,Ydot0+t24,Ydot0,Ydot0,Ydot0,Ydot0,t2,Ydot0,Ydot0,Ydot0],[6,6]);
