function d2Mda = EQd2Mda(a,mu,t0,tf)
%EQD2MDA
%    D2MDA = EQD2MDA(A,MU,T0,TF)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    06-Mar-2019 12:47:28

d2Mda = 1.0./a.^6.*mu.*1.0./sqrt(1.0./a.^5.*mu).*(t0-tf).*(-1.5e1./4.0);
