function dRdOE = EQdRdOE_Analytical_J2avg(J2,R,a,e,i,mu)
%EQDRDOE_ANALYTICAL_J2AVG
%    DRDOE = EQDRDOE_ANALYTICAL_J2AVG(J2,R,A,E,I,MU)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    20-Nov-2018 22:45:52

t2 = sin(i);
t3 = R.^2;
t4 = e.^2;
t5 = -t4+1.0;
t6 = t2.^2;
t7 = t6.*3.0;
t8 = t7-2.0;
t9 = 1.0./a.^3;
t10 = 1.0./t5.^(3.0./2.0);
dRdOE = [J2.*1.0./a.^4.*mu.*t3.*t8.*t10.*(3.0./4.0),J2.*e.*mu.*t3.*1.0./t5.^(5.0./2.0).*t8.*t9.*(-3.0./4.0),J2.*mu.*t2.*t3.*t9.*t10.*cos(i).*(-3.0./2.0),0.0,0.0,0.0];
