function a_Drag = EQDragEOM(A,Cd,H,h,h0,m,rho0,thetadot,x,xdot,y,ydot,zdot)
%EQDRAGEOM
%    A_DRAG = EQDRAGEOM(A,CD,H,H,H0,M,RHO0,THETADOT,X,XDOT,Y,YDOT,ZDOT)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    25-Feb-2019 13:09:03

t2 = abs(zdot);
t3 = thetadot.*y;
t4 = t3+xdot;
t5 = abs(t4);
t11 = thetadot.*x;
t12 = -t11+ydot;
t6 = abs(t12);
t7 = 1.0./m;
t8 = 1.0./H;
t9 = h-h0;
t18 = t8.*t9;
t10 = exp(-t18);
t13 = t2.^2;
t14 = t5.^2;
t15 = t6.^2;
t16 = t13+t14+t15;
t17 = sqrt(t16);
a_Drag = [A.*Cd.*rho0.*t4.*t7.*t10.*t17.*(-1.0./2.0);A.*Cd.*rho0.*t7.*t10.*t12.*t17.*(-1.0./2.0);A.*Cd.*rho0.*t7.*t10.*t17.*zdot.*(-1.0./2.0)];
