function a_J2 = EQJ2EOM(J2,R,mu,x,y,z)
%EQJ2EOM
%    A_J2 = EQJ2EOM(J2,R,MU,X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    25-Feb-2019 13:08:58

t2 = z.^2;
t3 = R.^2;
t4 = x.^2;
t5 = y.^2;
t6 = t2+t4+t5;
t7 = 1.0./t6.^(7.0./2.0);
t8 = 1.0./t6;
t9 = t2.*t8;
t10 = t9-1.0./3.0;
t11 = 1.0./t6.^(5.0./2.0);
a_J2 = [J2.*mu.*t2.*t3.*t7.*x.*3.0+J2.*mu.*t3.*t10.*t11.*x.*(9.0./2.0);J2.*mu.*t2.*t3.*t7.*y.*3.0+J2.*mu.*t3.*t10.*t11.*y.*(9.0./2.0);J2.*mu.*t3.*1.0./t6.^(3.0./2.0).*(t8.*z.*2.0-t2.*1.0./t6.^2.*z.*2.0).*(-3.0./2.0)+J2.*mu.*t3.*t10.*t11.*z.*(9.0./2.0)];
