function a_J3 = EQJ3EOM(J3,R,mu,x,y,z)
%EQJ3EOM
%    A_J3 = EQJ3EOM(J3,R,MU,X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    25-Feb-2019 13:08:46

t2 = R.^2;
t3 = z.^2;
t4 = x.^2;
t5 = y.^2;
t6 = t3+t4+t5;
t7 = 1.0./t6.^(3.0./2.0);
t8 = 1.0./t6.^(5.0./2.0);
t9 = 1.0./t6.^2;
t10 = 1.0./sqrt(t6);
t11 = t10.*z.*3.0;
t14 = t3.*t7.*z.*5.0;
t12 = t11-t14;
t13 = 1.0./t6.^3;
a_J3 = [J3.*R.*mu.*t2.*t9.*(t7.*x.*z.*3.0-t3.*t8.*x.*z.*1.5e1).*(-1.0./2.0)-J3.*R.*mu.*t2.*t12.*t13.*x.*2.0;J3.*R.*mu.*t2.*t9.*(t7.*y.*z.*3.0-t3.*t8.*y.*z.*1.5e1).*(-1.0./2.0)-J3.*R.*mu.*t2.*t12.*t13.*y.*2.0;(J3.*R.*mu.*t2.*t9.*(t10.*3.0-t3.*t7.*1.8e1+t3.^2.*t8.*1.5e1))./2.0-J3.*R.*mu.*t2.*t12.*t13.*z.*2.0];
