function Lbrack = EQLbrack_Analytical(a,e,i,mu)
%EQLBRACK_ANALYTICAL
%    LBRACK = EQLBRACK_ANALYTICAL(A,E,I,MU)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    20-Nov-2018 22:51:01

t2 = 1.0./a;
t3 = e.^2;
t4 = -t3+1.0;
t5 = sqrt(t4);
t6 = mu.*t2;
t7 = 1.0./sqrt(t6);
t8 = cos(i);
t9 = 1.0./sqrt(t4);
t10 = e.*mu.*t7.*t9;
t11 = e.*mu.*t7.*t8.*t9;
t12 = sin(i);
t13 = sqrt(t6);
t14 = a.*t5.*t12.*t13;
Lbrack = reshape([0.0,0.0,0.0,(mu.*t2.*t5.*t7)./2.0,(mu.*t2.*t5.*t7.*t8)./2.0,(mu.*t2.*t7)./2.0,0.0,0.0,0.0,-t10,-t11,0.0,0.0,0.0,0.0,0.0,-t14,0.0,mu.*t2.*t5.*t7.*(-1.0./2.0),t10,0.0,0.0,0.0,0.0,mu.*t2.*t5.*t7.*t8.*(-1.0./2.0),t11,t14,0.0,0.0,0.0,mu.*t2.*t7.*(-1.0./2.0),0.0,0.0,0.0,0.0,0.0],[6,6]);
