function U_J2 = EQU_Analytical_J2(J2,M,R,a,e,i,mu,omega)
%EQU_ANALYTICAL_J2
%    U_J2 = EQU_ANALYTICAL_J2(J2,M,R,A,E,I,MU,OMEGA)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    20-Nov-2018 22:45:30

t2 = sin(i);
t3 = e.^2;
t4 = omega.*2.0;
t5 = t3.^2;
t6 = t2.^2;
t7 = M.*2.0;
U_J2 = -R.^2.*1.0./a.^3.*mu.*((t6.*(3.0./4.0)-1.0./2.0).*(J2.*1.0./(-t3+1.0).^(3.0./2.0)+J2.*cos(t7).*(t3.*(9.0./2.0)+t5.*(7.0./2.0))+J2.*cos(M).*(e.*3.0+e.*t3.*(2.7e1./8.0)))-t6.*(J2.*cos(t4+t7).*(t3.*(-5.0./2.0)+t5.*(1.3e1./1.6e1)+1.0)-J2.*cos(M+t4).*(e./2.0-(e.*t3)./1.6e1)+J2.*cos(M.*4.0+t4).*(t3.*(1.7e1./2.0)-t5.*(1.15e2./6.0))+J2.*cos(M.*3.0+t4).*(e.*(7.0./2.0)-e.*t3.*(1.23e2./1.6e1))).*(3.0./4.0));
