function U_J2avg = EQU_Analytical_J2avg(J2,R,a,e,i,mu)
%EQU_ANALYTICAL_J2AVG
%    U_J2AVG = EQU_ANALYTICAL_J2AVG(J2,R,A,E,I,MU)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    20-Nov-2018 22:45:39

t2 = sin(i);
U_J2avg = J2.*R.^2.*1.0./a.^3.*mu.*1.0./(-e.^2+1.0).^(3.0./2.0).*(t2.^2.*3.0-2.0).*(-1.0./4.0);
